language: python

notifications:
  email: false

branches:
  only:
  - main

jobs:
  include:
    - sudo: required
      services:
        - docker
      env: DOCKER_IMAGE=jdgalileo/galileo:devel-cpu
           BUILD_TARGET=cpu
    - sudo: required
      services:
        - docker
      env: DOCKER_IMAGE=jdgalileo/galileo:devel-gpu
           BUILD_TARGET=gpu

install:
  - docker pull $DOCKER_IMAGE

script:
  - docker run --rm -e BUILD_TARGET=$BUILD_TARGET -v `pwd`:/workspace $DOCKER_IMAGE bash /workspace/docker/build_wheel.sh
  - ls dist
