name: BuildGalileo
on:
  push:
    branches: [ main ]
    paths-ignore:
      - conda/**
      - docker/**
      - docs/**
      - examples/**
      - testdata/**
  pull_request:
    branches: [ main ]
    paths-ignore:
      - conda/**
      - docker/**
      - docs/**
      - examples/**
      - testdata/**
  workflow_dispatch:

jobs:
  build_and_test:
    name: build and test Galileo in docker container
    runs-on: ubuntu-latest
    container: jdgalileo/galileo:devel-cpu
    steps:
      - name: check out code
        uses: actions/checkout@v2
        with:
          ref: JDGalileo-patch-1
          submodules: true
      - name: build
        run: |
          bash ./build.sh
          python3 -c "import galileo; import galileo.tf"
      - name: test
        run: bash ./galileo/tests/run_tests.sh
