name: BuildGalileo
on:
  push:
    branches: [ main ]
    paths-ignore:
      - conda/**
      - docker/**
      - docs/**
      - examples/**
      - testdata/**
  pull_request:
    branches: [ main ]
    paths-ignore:
      - conda/**
      - docker/**
      - docs/**
      - examples/**
      - testdata/**
  workflow_dispatch:

jobs:
  build_and_test:
    name: build and test Galileo in docker container
    runs-on: ubuntu-latest
    container: jdgalileo/galileo:devel-cpu
    steps:
      - name: check out code
        uses: actions/checkout@v2
        with:
          ref: main
          submodules: true
      - name: build
        run: |
          ls
          python --verison
          python3 --verison
          g++ --version
        shell: bash
      - name: test
        run: |
          ls
          pytest --verison
        shell: bash
      
