name: BuildGalileo
on:
  push:
    branches: [ main ]
    paths-ignore:
      - conda/**
      - docker/**
      - docs/**
      - examples/**
      - testdata/**
  pull_request:
    branches: [ main ]
    paths-ignore:
      - conda/**
      - docker/**
      - docs/**
      - examples/**
      - testdata/**
  workflow_dispatch:

jobs:
  build_and_test:
    name: build and test Galileo in docker container
    runs-on: ubuntu-latest
    container: jdgalileo/galileo:devel-cpu
    steps:
      - name: check out code
        uses: actions/checkout@v2
        with:
          ref: main
          submodules: true
      - name: build
        run: |
          source ./build.sh
          echo $LIBRARY_PATH
          export LIBRARY_PATH=/lib64:/usr/local/lib:/usr/local/lib64:/usr/lib/jvm/java/jre/lib/amd64/server:/opt/hadoop/lib/native
          python3 setup.py build
          python3 setup.py install
          python3 -c "import galileo; import galileo.tf"
      - name: test
        run: bash ./galileo/tests/run_tests.sh
